
version: 2

models:
  - name: birv_account_x_party_dim
    description: "A starter dbt model"
    columns:
      - name: account_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: joined_account_status
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null